### ISSUE TITLE
language field don't appear in datasource filter

### ISSUE THREAD

**Issue by ghost** [DeuxHuitHuit/languages#1]
More info http://www.getsymphony.com/discuss/thread/106007/

**Comment by vlad-ghita** [comment]
Want my honest opinion? I think you're building it the wrong way.

For multilingual sites:
1. Install [Languages](http://symphonyextensions.com/extensions/languages/) -> supplies the languages
2. Install [Frontend Localisation](http://symphonyextensions.com/extensions/frontend_localisation/) -> base extension for multilanguage
3. Install [Flang Detection gTLDs](http://symphonyextensions.com/extensions/flang_detection_gtlds/) -> allows language in the URL right after the domain like `www.site.com/en/`
4. Install [Page LHandles](http://symphonyextensions.com/extensions/page_lhandles/) -> localise Page handles and titles
5. Install any other [Multilingual](http://symphonyextensions.com/extensions/?keywords=multilingual&type=&compatible-with=&sort=updated&order=desc) field, like TextBox etc

Unfortunately, I don't have the time to implement what you're asking.

I'll leave this open. If it gets some votes up, perhaps I will find some time. Or perhaps someone else wants to do it.

**Comment by jmoont** [comment]
I have added a pull request that adds this feature.

**Comment by nitriques** [comment]
Thanks. Fixed via #2
