### ISSUE TITLE
compatibility with Symphony 2.6.2

### ISSUE THREAD

**Issue by cmnstmntmn** [DeuxHuitHuit/languages#3]
is this planned for near future?

`Warning: Uncaught exception 'ErrorException' with message 'require_once(/Users/ctin/repos/w/extensions/image_upload/fields/field.image_upload.php): failed to open stream: No such file or directory' in /Users/ctin/repos/w/extensions/multilingual_image_upload/fields/field.multilingual_image_upload.php:7 Stack trace: #0 /Users/ctin/repos/w/extensions/multilingual_image_upload/fields/field.multilingual_image_upload.php(7): GenericErrorHandler::handler(2, 'require_once(/U...', '/Users/ctin/rep...', 7, Array) #1 /Users/ctin/repos/w/extensions/multilingual_image_upload/fields/field.multilingual_image_upload.php(7): require_once() #2 /Users/ctin/repos/w/symphony/lib/toolkit/class.fieldmanager.php(574): require_once('/Users/ctin/rep...') #3 /Users/ctin/repos/w/symphony/content/content.blueprintssections.php(483): FieldManager::create('multilingual_im...') #4 /Users/ctin/repos/w/symphony/lib/toolkit/class.administrationpage.php(705): contentBlueprintsSections->__viewEdit(NULL) #5 /Users/ctin/repos/w/symphony/lib/toolkit/class.a in /Users/ctin/repos/w/extensions/multilingual_image_upload/fields/field.multilingual_image_upload.php on line 7`

`Fatal error: main(): Failed opening required '/Users/ctin/repos/w/extensions/image_upload/fields/field.image_upload.php' (include_path='.:/usr/local/Cellar/php56/5.6.2/lib/php') in /Users/ctin/repos/w/extensions/multilingual_image_upload/fields/field.multilingual_image_upload.php on line 7`

**Comment by nitriques** [comment]
This should work with all the latest versions. Please reopen if needed.
